oc_platform_home:
    path:     /index
    defaults: { _controller: OCPlatformBundle:Advert:index  }

oc_platform_produit:
    path:     /produit
    defaults: { _controller: OCPlatformBundle:Advert:produit }
    #template: 'OCPlatformBundle:Static:produit.html.twig'


oc_platform_hamburger:
     path:     /hamburger
     defaults: { _controller: OCPlatformBundle:Advert:hamburger }

oc_platform_dessert:
     path:     /dessert
     defaults: { _controller: OCPlatformBundle:Advert:dessert }


oc_platform_contact:
    path:     /contact
    defaults: { _controller: OCPlatformBundle:Advert:contact  }

oc_platform_blog:
    path:     /blog/{page}
    defaults: { _controller: OCPlatformBundle:Advert:blog, page: 1  }
    requirements:
            page: \d*

oc_platform_panier:
    path:     /panier
    defaults: { _controller: OCPlatformBundle:Advert:panier  }


oc_platform_view:
    path:     /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view  }

oc_platform_ajouter:
    path:     /ajouter/{id}
    defaults: {_controller:OCPlatformBundle:Advert:ajouter  }

oc_platform_supprimer:
    path:     /supprimer/{id}
    defaults: {_controller:OCPlatformBundle:Advert:supprimer  }

oc_platform_edit:
    path:     /edit/{id}
    defaults: { _controller:OCPlatformBundle:Advert:add }
    requirements:
        id: \d+

oc_platform_delete:
    path:     /delete/{id}
    defaults: { _controller:OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+

oc_platform_menu:
    path:     /menu
    defaults: {_controller:OCPlatformBundle:Advert:menu  }

oc_platform_paiement:
    path:     /paiement
    defaults: {_controller:OCPlatformBundle:Advert:paiement  }