oc_platform_home:
    path:     /index
    defaults: { _controller: OCPlatformBundle:Advert:index  }

oc_platform_produit:
    path:     /produit
    defaults: { _controller: OCPlatformBundle:Advert:produit  }

oc_platform_contact:
    path:     /contact
    defaults: { _controller: OCPlatformBundle:Advert:contact  }

oc_platform_blog:
    path:     /blog/{page}
    defaults: { _controller: OCPlatformBundle:Advert:blog, page: 1  }
    requirements:
            page: \d*

oc_platform_view:
    path:     /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view  }

oc_platform_add:
    path:     /add
    defaults: {_controller:OCPlatformBundle:Advert:add  }

oc_platform_edit:
    path:     /edit/{id}
    defaults: { _controller:OCPlatformBundle:Advert:add }
    requirements:
        id: \d+

oc_platform_delete:
    path:     /delete/{id}
    defaults: { _controller:OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+